### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by candrsn** [atom/deprecation-cop#38] opened 2015-04-26 18:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.19.4-200.fc21.x86_64
**Thrown From**: [deprecation-cop](https://github.com/atom/deprecation-cop) package, v0.32.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/local/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11

TypeError: undefined is not a function
  at module.exports.eachSelector (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11:18)
  at SelectorLinter.module.exports.SelectorLinter.checkUIStylesheet (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:75:7)
  at SelectorLinter.module.exports.SelectorLinter.checkPackage (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:56:30)
  at Object.exports.getSelectorDeprecations (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:14:14)
  at exports.getSelectorDeprecationsCount (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:22:41)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.getDeprecatedSelectorCount (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:70:115)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.update (/usr/local/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:80:52)
  at /usr/local/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:3:61
  at Object.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at global.__grim__.deprecate (/usr/local/share/atom/resources/app/node_modules/grim/lib/grim.js:70:21)
  at Atom.Object.defineProperty.get (/usr/local/share/atom/resources/app/src/atom.js:55:11)
  at /home/candrsn/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:199:13
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -0:00.0 core:move-up (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-jedi",
      "autocomplete-css",
      "npm-autocomplete",
      "autocomplete",
      "linter",
      "autocomplete-plus-python-jedi"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.3.0
autocomplete-glsl, v0.2.1
autocomplete-plus, v2.12.0
closure-linter, v0.2.5
compass, v0.7.5
git-diff-details, v0.18.0
git-go, v1.0.1
git-log, v0.3.0
git-projects, v1.13.0
git-tab-status, v1.7.0
linter-pylint, v0.2.1
linter-python-pyflakes, v0.1.0
minimap, v4.7.6
open-last-project, v0.4.1
project-manager, v1.15.5
project-view, v0.1.2
python, v0.5.1
python-coverage, v0.2.0
python-jedi, v0.2.0
recent-projects, v0.3.0
tualo-git-context, v0.3.0
vim-mode, v0.44.0
virtualenv, v0.6.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-04-27 17:22
This is a duplicate of https://github.com/atom/deprecation-cop/issues/22

If you upgrade to the latest version of Atom you will no longer see this issue.

**Closed by kevinsawicki** 2015-04-27 17:22 UTC
