### ISSUE TITLE
Search similar issues before creating it

### ISSUE THREAD

**Issue by matiasgarciaisaia** [atom/deprecation-cop#21] opened 2015-01-19 19:48 UTC
I'm not _that_ sure about how to implement this, but plugins repos are getting flooded with duplicate issues reported by deprecation-cop (see, for example, thomaslindstrom/color-picker#49, thomaslindstrom/color-picker#48, thomaslindstrom/color-picker#50 and thomaslindstrom/color-picker#52).

May be querying GitHub's api to check if there already is an issue with the same subject would work - as the subjects are being auto-generated.

**Comment by 50Wliu** [comment] 2015-01-19 20:12
This might be best handled in the [notifications](https://github.com/atom/notifications) repo since that's the package that asks users to submit a bug report.  Could you reopen this issue over there?

**Comment by matiasgarciaisaia** [comment] 2015-01-19 20:18
Thanks, @50Wliu - it seems there's already an issue for this there.

**Comment by benogle** [comment] 2015-01-19 20:21
This is slightly different. Deprecation cop has a link in the interface that is always `create issue on *`. No searching happens.

**Comment by 50Wliu** [comment] 2015-01-19 20:30
Oh, sorry.  That's what I get for being on 0.172.0 and being too lazy to upgrade ;P.

**Comment by benogle** [comment] 2015-01-19 20:31
no prob

**Comment by joefitzgerald** [comment] 2015-02-04 15:59
Oh man would I love for some searching to happen prior to redirecting the user. I've had people create about 20 dupes over the past day because of the `atom.services` deprecation. Most assume some checking already occurs, and then feel bad for creating the dupes once they are made aware.

Not absolutely essential, but certainly a nice to have.

**Comment by mik01aj** [comment] 2015-02-06 15:17
+1. I just created another dupe and deleted it after a while.

**Comment by lee-dohm** [comment] 2015-02-06 16:25
I've thought about a dupe finder service that basically uses Bayesian pattern matching to determine if a given bunch of text is a dupe of a currently open or closed bug. It would be best at finding the ones that people report often, of course, but I think that would be the biggest bang for the buck anyway.

Yet another one of those projects that I need to find time to get around to one day.

**Comment by matiasgarciaisaia** [comment] 2015-02-06 16:48
Just finding exact-matching title's would be a great improvement - since Atom is on the run to 1.0, lots of issues are being created from that button. A better, long term solution would be great, but I think that a quick fix would help a lot now.

**Comment by benogle** [comment] 2015-02-06 18:05
> I've thought about a dupe finder service that basically uses Bayesian pattern matching to determine if a given bunch of text is a dupe of a currently open or closed bug.

I like this idea. Even a module that does something naive like notifications would be nice. It would be good to have something reusable. I think it should just be an npm module, though, rather than some package that needs to be installed (unless it's in the core dist?).

**Comment by lee-dohm** [comment] 2015-02-06 22:35
@benogle I agree that an npm module would probably be best. I was thinking of a web service for the full-on Bayesian thing so that each Atom instance wouldn't have to calculate the word frequencies themselves. But if we start with something naïve then putting it client side wouldn't be a big deal. (Except for perhaps people with slow network connections?)

**Comment by mik01aj** [comment] 2015-02-09 10:28
This awesome intelligent bayesian search approach sure would be great, but I'm totally against waiting for it. Let's implement exact string matching now. I believe that exact matching would be right in 90% of the cases, because usually people leave whatever issue title was suggested.

**Closed** 2015-05-19 01:57 UTC
Labels: enhancement
