### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bcrahul** [atom/deprecation-cop#40] opened 2015-04-29 18:04 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-51-generic
**Thrown From**: [deprecation-cop](https://github.com/atom/deprecation-cop) package, v0.32.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11

TypeError: undefined is not a function
  at module.exports.eachSelector (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11:18)
  at SelectorLinter.module.exports.SelectorLinter.checkSyntaxStylesheet (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:102:7)
  at SelectorLinter.module.exports.SelectorLinter.checkPackage (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:54:30)
  at Object.exports.getSelectorDeprecations (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:14:14)
  at exports.getSelectorDeprecationsCount (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:22:41)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.getDeprecatedSelectorCount (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:70:115)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.update (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:80:52)
  at /usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:3:61
  at Object.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at global.__grim__.deprecate (/usr/share/atom/resources/app/node_modules/grim/lib/grim.js:70:21)
  at Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
  at LintStatusView.module.exports.LintStatusView.getActiveLintRunner (/home/rahul/.atom/packages/atom-lint/lib/lint-status-view.coffee:27:22)
  at LintStatusView.module.exports.LintStatusView.subscribeToLintRunner (/home/rahul/.atom/packages/atom-lint/lib/lint-status-view.coffee:31:25)
  at /home/rahul/.atom/packages/atom-lint/lib/lint-status-view.coffee:23:10
  at process._tickCallback (node.js:386:11)

```

### Commands

```
  5x -4:31.9 wheel (atom-text-editor.editor.is-focused)
  2x -4:30.4 active-buffer-changed (status-bar.status-bar)
undefined -4:27.0 wheel (atom-text-editor.editor.is-focused)
     -3:35.5 active-buffer-changed (status-bar.status-bar)
 46x -3:32.0 wheel (atom-text-editor.editor)
     -3:28.5 active-buffer-changed (status-bar.status-bar)
undefined -1:24.3 wheel (atom-text-editor.editor.is-focused)
     -1:10.8 grammar-selector:show (atom-text-editor.editor.is-focused)
 30x -1:03.8 wheel (atom-text-editor.editor.is-focused)
     -0:59.5 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -0:59.4 active-buffer-changed (status-bar.status-bar)
     -0:19.6 core:confirm (atom-text-editor.editor.mini)
  2x -0:06.2 core:backspace (atom-text-editor.editor.mini)
     -0:05.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 active-buffer-changed (status-bar.status-bar)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-python",
      "language-ruby-on-rails",
      "language-toml",
      "language-perl",
      "language-java",
      "language-go",
      "language-clojure"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
compare-files, v0.4.1
linter, v0.12.1
linter-csslint, v0.0.11
linter-xmllint, v0.0.5
pretty-json, v0.3.3
seti-syntax, v0.4.0
seti-ui, v0.6.3
view-tail-large-files, v0.1.14

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment] 2015-04-29 18:30
This is a duplicate of https://github.com/atom/deprecation-cop/issues/22, I believe.

If you upgrade to the latest version of Atom (0.194.0) you will no longer see this issue.

**Closed by izuzak** 2015-04-29 18:30 UTC

**Comment by bcrahul** [comment] 2015-04-29 18:48
Thank you.
