### ISSUE TITLE
Cop not catching a deprecated call

### ISSUE THREAD

**Issue by travs** [atom/deprecation-cop#20] opened 2015-01-18 23:14 UTC
Someone reported [an issue](https://github.com/travs/markdown-pdf/issues/29) with my package that was caught using the deprecation cop. I was using the workspaceView class which has since been deprecated; the trouble is that when I run the deprecation cop I don't see this error in my package.

I have checked, and I do indeed use the deprecated call, so why is the cop not catching this?

Note: Another package I am using (`color-picker`) uses the same deprecated call (`workspaceView`), and the cop catches this on my system. Not sure if/how this would be related, but I thought I should include it.

I'm using Atom v0.174.0, deprecation cop v0.32.0, on OS X Yosemite 10.10.1

If there is anything I can do to help let me know!

**Comment by kevinsawicki** [comment] 2015-02-03 00:47
Is this still happening with the latest version of your package or only previous versions? If so, which version did the deprecation not show up for?

**Comment by kevinsawicki** [comment] 2015-02-19 17:30
Just wanted to check back in and see if this was still an issue.

**Comment by travs** [comment] 2015-02-19 19:27
Hi @kevinsawicki 

This is no longer an issue since I fixed the deprecated calls that someone else reported, but I have not tested deprecation cop with the new version of Atom and the old version of my package (v1.2.12 when this issue was reported).

**Comment by izuzak** [comment] 2015-04-28 06:42
@travs I just tried installing v1.2.12 of your package (the version which had the deprecated calls) on the latest Atom version (0.195.0-3c2acdc), and the workspaceView calls are being correctly reported in Deprecation Cop.

![screen shot 2015-04-27 at 23 32 32](https://cloud.githubusercontent.com/assets/38924/7358470/be755e82-ed35-11e4-94fd-f5f2454cbb47.png)

I'm not sure why those calls weren't reported at all before when you tried it. Is it possible that you just installed the package and started Atom, but didn't run the package's activation command to trigger activation? If that's so, then that would explain things -- if you don't use the package and it's not activated, then calls to most deprecated APIs/features won't be caught because nothing triggered them yet (in other words, those deprecated calls need to be triggered at runtime for them to be caught by Deprecation Cop).

I'm going to close this, but if anyone runs into this again -- please let us know and provide steps to reproduce (which version of Atom you're using, which package, the version of the package, and which deprecated API call is not caught).

**Closed by izuzak** 2015-04-28 06:42 UTC
Labels: bug
